/********************************************************************
* src/BackgroundEstimator/BackgroundEstimator_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/BackgroundEstimator/BackgroundEstimator_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableBackgroundEstimator_Dict();
extern void G__cpp_setup_inheritanceBackgroundEstimator_Dict();
extern void G__cpp_setup_typetableBackgroundEstimator_Dict();
extern void G__cpp_setup_memvarBackgroundEstimator_Dict();
extern void G__cpp_setup_globalBackgroundEstimator_Dict();
extern void G__cpp_setup_memfuncBackgroundEstimator_Dict();
extern void G__cpp_setup_funcBackgroundEstimator_Dict();
extern void G__set_cpp_environmentBackgroundEstimator_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/BackgroundEstimator.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BackgroundEstimator_DictLN_TClass;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TBuffer;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TMemberInspector;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_string;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TFile;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TH1F;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_TH2F;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_fitsfile;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BackgroundEstimator_DictLN_BackgroundEstimator;

/* STUB derived class for protected member access */
